force-app/main/default/objects/Public_File__c/Public_File__c.object-meta.xml
<CustomObject>
    <label>Public File</label>
    <nameField>
        <label>Public File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_File__c/fields/File_Identifier__c.field-meta.xml
<CustomField>
    <fullName>File_Identifier__c</fullName>
    <label>File Identifier</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Public_File__c/fields/Original_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_File_Name__c</fullName>
    <label>Original File Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Public_File__c/fields/Sharing_URL__c.field-meta.xml
<CustomField>
    <fullName>Sharing_URL__c</fullName>
    <label>Sharing URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/publicFileController.cls
public with sharing class publicFileController {
    @AuraEnabled
    public static string createSharing(String documentId, String fileName, String recordId) {
        
        ContentDocument thisDocTitle = [SELECT Title FROM ContentDocument WHERE Id =:documentId];
        
        if (String.isBlank(fileName)) {
            fileName = thisDocTitle.Title;
        }

        ContentVersion thisDocVers = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:documentId AND IsLatest = TRUE];
        
        ContentDistribution newDistribution = new ContentDistribution(ContentVersionId=thisDocVers.Id, Name=fileName, RelatedRecordId=recordId, PreferencesAllowOriginalDownload=True, PreferencesAllowPDFDownload=True, PreferencesAllowViewInBrowser=True, PreferencesLinkLatestVersion=True, PreferencesNotifyOnVisit=False, PreferencesNotifyRndtnComplete=False);
        insert newDistribution;
        system.debug(newDistribution);

        ContentDistribution thisDistribution = [SELECT Id, DistributionPublicUrl FROM ContentDistribution WHERE Id= :newDistribution.Id];
        
        Public_File__c thisPublicFile = new Public_File__c(Id=recordId, Name=fileName, File_Identifier__c=documentId, Original_File_Name__c=thisDocTitle.Title, Sharing_URL__c=thisDistribution.DistributionPublicUrl);
        update thisPublicFile;

        String returnId = thisDistribution.Id;
        return returnId;
    }

    @AuraEnabled
    public static string moveFileCreateSharing(String documentId, String fileName, String recordId) {
        
        ContentDocumentLink docLink = new ContentDocumentLink(ContentDocumentId=documentId, LinkedEntityId=recordId);
        system.debug(docLink);
        insert docLink;

        
        ContentDocument thisDocTitle = [SELECT Title FROM ContentDocument WHERE Id =:documentId];
        
        if (String.isBlank(fileName)) {
            fileName = thisDocTitle.Title;
        }

        ContentVersion thisDocVers = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:documentId AND IsLatest = TRUE];
        
        ContentDistribution newDistribution = new ContentDistribution(ContentVersionId=thisDocVers.Id, Name=fileName, RelatedRecordId=recordId, PreferencesAllowOriginalDownload=True, PreferencesAllowPDFDownload=True, PreferencesAllowViewInBrowser=True, PreferencesLinkLatestVersion=True, PreferencesNotifyOnVisit=False, PreferencesNotifyRndtnComplete=False);
        insert newDistribution;
        system.debug(newDistribution);

        ContentDistribution thisDistribution = [SELECT Id, DistributionPublicUrl FROM ContentDistribution WHERE Id= :newDistribution.Id];
        
        Public_File__c thisPublicFile = new Public_File__c(Id=recordId, Name=fileName, File_Identifier__c=documentId, Original_File_Name__c=thisDocTitle.Title, Sharing_URL__c=thisDistribution.DistributionPublicUrl);
        update thisPublicFile;

        String returnId = thisDistribution.Id;
        return returnId;
    }
}