force-app/main/default/objects/Public_File__c/Public_File__c.object-meta.xml
<CustomObject>
    <label>Public File</label>
    <nameField>
        <label>Public File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_File__c/fields/File_Identifier__c.field-meta.xml
<CustomField>
    <fullName>File_Identifier__c</fullName>
    <label>File Identifier</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Public_File__c/fields/Sharing_URL__c.field-meta.xml
<CustomField>
    <fullName>Sharing_URL__c</fullName>
    <label>Sharing URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PublicFileSearchController.cls
public with sharing class PublicFileSearchController {
    @AuraEnabled
    public static List<Public_File__c> loadFiles(String searchTerm, String value, String field) {

        if (searchTerm == null) {
            searchTerm = '%';
        } else {
            searchTerm = searchTerm.trim();
            searchTerm = '%'+ searchTerm + '%';
        }

        if (value == null) {
            value = '%';
        } else if (value == '') {
            value = '%';
        }

        system.debug('term='+searchTerm+' value='+value+' field='+field);

        if (field == null) {
            list<Public_File__c> files = Database.query('SELECT Id, Name, File_Identifier__c, Sharing_URL__c FROM Public_File__c WHERE Name LIKE :searchTerm ORDER BY Name ASC LIMIT 3');
            system.debug('null');
            return files;
        } else if (field == '') {
            list<Public_File__c> files = Database.query('SELECT Id, Name, File_Identifier__c, Sharing_URL__c FROM Public_File__c WHERE Name LIKE :searchTerm ORDER BY Name ASC LIMIT 3');
            system.debug('empty');
            return files;
        } else {
            list<Public_File__c> files = Database.query('SELECT Id, Name, File_Identifier__c, Sharing_URL__c FROM Public_File__c WHERE ' + field + ' LIKE :value AND Name LIKE :searchTerm ORDER BY Name ASC LIMIT 3');
            system.debug('category');
            return files;
        }

        
    }
}